---
- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present

- name: Install apt-listchanges
  package:
    name: apt-listchanges
    state: present

- name: Configure auto-upgrades
  template:
    src: 22auto-upgrades-local.j2
    dest: /etc/apt/apt.conf.d/22auto-upgrades-local
    owner: root
    group: root
    mode: '0644'

- name: Configure unattended-upgrades
  template:
    src: 52unattended-upgrades-local.j2
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
    owner: root
    group: root
    mode: '0644'
